site_name: Dropshipping 101
copyright: ©QUSEIT.com 2021
repo_url: https://github.com/mainium/dropshiper

theme: 
  name: 'solar'
  custom_dir: '_theme/mkdocs_bootswatch/solar'

nav:
  - Home: index.md
  - '中文版': 
    - '第0章': zh/ch00.md
    - '第1章': zh/ch01.md
    - '第2章': zh/ch02.md
    - '第12章': zh/ch12.md
  - '小百科': 
    - '追加/交叉销售的不同': zh/diff-upselling-cross-selling.md


#  - ANN: announce.md
#  - User Guide: guide.md

markdown_extensions:
  - toc:
      permalink: "¶"

extra:
  logo: img/logo.jpg
  include_toc: yes
  extra_nav_links:
    Fork me on GitHub: https://github.com/mainium/demo


